---
- name: install SELinux for Python
  yum: 
    name: libselinux-python 
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Install git
  yum: 
    name: git
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: enable SELinux
  selinux: 
    policy: targeted
    state: enforcing