---
- name: install SELinux for Python
  yum: 
    name: libselinux-python 
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Install git
  yum: 
    name: git
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: enable SELinux
  selinux: 
    policy: targeted
    state: enforcing

- name: Install nginx
  yum: 
    name: nginx
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: Ensure document root exists
  file: 
    path: "/nginx"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755

- name: enable port 8888 for HTTP binding
  seport: 
    ports: "8888" 
    proto: tcp 
    setype: http_port_t 
    state: present
    reload: yes

- name: clone source repo
  git: 
    repo: "{{tech_quiz_repo}}"
    dest: "~/tech_quiz/"
    force: yes

- name: copy index.html to nginx root
  command: mv "~/tech_quiz/index.html" "/nginx/index.html"

- name: "set user, owner, and permissions on index.html"
  file: 
    path: "/nginx"
    state: directory
    owner: nginx
    group: nginx
    mode: 0755
    setype: httpd_sys_content_t
    seuser: system_u
    recurse: yes

- name: Install config file
  template: 
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: restart nginx